import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="prose prose-lg mx-auto">
          <h1 className="text-4xl font-bold mb-8 text-center">ToonGen Terms of Service</h1>
          <p className="text-gray-500 mb-8 text-center">Last updated: May 14, 2025</p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>
            By using the ToonGen app, you agree to comply with and be bound by these Terms of Service.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">2. In-App Purchases</h2>
          <p>
            To use the photo-to-cartoon conversion feature, users need to purchase a premium subscription.
          </p>
          <p>
            a. We offer two subscription models: Weekly Premium (₹690/week) and Annual Premium (₹2550/year).
          </p>
          <p>
            While premium users have unlimited access to the photo-to-cartoon conversion features, fair usage policies may apply. To ensure a high-quality experience for all users, rate limits may be implemented if usage significantly exceeds typical patterns. These limits are designed to be generous and should not impact regular usage.
          </p>
          <p>
            b. We reserve the right to change the pricing, subscription terms, or benefits associated with in-app purchases. Any such changes will be communicated through the app or on our website.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">3. Usage Limitations</h2>
          <p>
            a. We reserve the right to limit the number of conversions and may change or terminate our services at any time.
          </p>
          <p>
            b. IMPORTANT: ToonGen is intended for creative and entertainment purposes only. The app's photo-to-cartoon conversion feature should NOT be relied upon for legal, financial, or professional advice. Users must exercise caution and verify information from credible sources when necessary.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">4. Intellectual Property</h2>
          <p>
            a. All content within the ToonGen app, including text, graphics, and code, is the property of Somasundaram M and is protected by copyright and other intellectual property laws.
          </p>
          <p>
            b. You may not reproduce, modify, or distribute any content from our app without our permission.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">5. Gemini AI API</h2>
          <p>
            We utilize the Gemini API to power some of our application's features. While we strive to provide the best service, we are not responsible for any errors, inaccuracies, or unavailability stemming from the Gemini API.
          </p>
          <p>
            Disclaimer: The photo-to-cartoon conversion results are generated by the Gemini API and may resemble existing cartoon styles or characters. Any similarity is purely coincidental and unintentional. The generated content is not endorsed by or affiliated with any cartoon creators, studios, or copyright holders. Users are responsible for ensuring that their use of the generated content complies with applicable copyright laws.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">6. Privacy</h2>
          <p>
            Your use of the app is subject to our <a href="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</a>, which outlines how we collect and use your data.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">7. Termination</h2>
          <p>
            We may terminate or suspend your access to the app at any time for any reason.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">8. Disclaimer of Warranty</h2>
          <p>
            We provide the app on an "as is" basis, without any warranties or representations.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">9. Limitation of Liability</h2>
          <p>
            a. We are not liable for any damages or losses resulting from your use of the app.
          </p>
          <p>
            b. By using ToonGen, you agree to hold harmless Somasundaram M, its employees, affiliates, and partners from any claims, damages, or expenses arising from your use of the app or any actions taken based on the information provided by the app.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">10. Contact Us</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at <a href="mailto:somasundaram.mahesh@gmail.com" className="text-blue-600 hover:underline">somasundaram.mahesh@gmail.com</a>.
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfService;